# Generated by Django 2.0.3 on 2018-05-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=255, verbose_name='一级目录')),
            ],
        ),
        migrations.CreateModel(
            name='error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('web_name', models.CharField(max_length=255, verbose_name='站点名称')),
                ('web_info', models.CharField(max_length=255, verbose_name='站点信息')),
                ('web_url', models.URLField(max_length=64, verbose_name='站点url')),
            ],
        ),
        migrations.CreateModel(
            name='root_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('root_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('root_passwd', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='subcat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcatname', models.CharField(max_length=255, verbose_name='二级目录')),
                ('sub_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serach.cat')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32, verbose_name='普通用户名')),
                ('user_passwd', models.CharField(max_length=64, verbose_name='普通密码')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='web_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serach.subcat'),
        ),
        migrations.AddField(
            model_name='link',
            name='web_type_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serach.cat'),
        ),
        migrations.AddField(
            model_name='error',
            name='err_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serach.link'),
        ),
    ]
