# Generated by Django 2.0.3 on 2018-05-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0003_link_url_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url_num',
        ),
    ]
