# Generated by Django 2.0.3 on 2018-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0004_remove_link_url_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url_num',
            field=models.IntegerField(default=0, max_length=16, verbose_name='访问数量'),
        ),
    ]
