# Generated by Django 2.0.3 on 2018-05-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0005_link_url_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url_num',
            field=models.IntegerField(default=0, verbose_name='访问数量'),
        ),
    ]
