# Generated by Django 2.0.3 on 2018-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0006_auto_20180526_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='web_info',
            field=models.CharField(max_length=1024, verbose_name='站点信息'),
        ),
        migrations.AlterField(
            model_name='link',
            name='web_url',
            field=models.URLField(max_length=255, verbose_name='站点url'),
        ),
    ]
